#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Oct 16 14:42:42 2024

@author: mr-arthor
"""
# =============================================================================
# 
# Tuples=("hello","world","why")
# # =============================================================================
# # print(type(Tuples))
# # =============================================================================
# print(Tuples)
# 
# 
# a= int (input("Enter A Number "))
# 
# print(a)
# 
# =============================================================================

# Update Method     It will add the elements of one set in another
set1 = {"PDGBA", "PGDAC" ,"PGDIT" , "Markile"}
set2 = {'Amit', "Tarun", "Mohit" ," Markile"}
set2 = set1.update (set2) # update ( ) method
print (set1)
